spring.application.name=salessavvy-backend
server.port=9090


spring.datasource.url=jdbc:mysql://localhost:3306/sales_savvy
spring.datasource.username=root
spring.datasource.password=Yaseen@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true

spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

jwt.secret=mysecretcodemysecretcodemysecretcodemysecretcodemysecretcodemysecretcode12345678

razorpay.key.id=rzp_test_TG2RJPmPoyrSBJ
razorpay.key.secret=B9xaAAtecfX6MDM0iW7l5mEg
